server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: catalog-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
    binding:
      listener:
        simple:
          queues:
            - name: ${queue.movie.name}
            - name: ${queue.serie.name}
    queues:
      - name: ${queue.movie.name}
        durable: true
      - name: ${queue.serie.name}
        durable: true
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

queue:
  movie:
    name: MovieQueue
  serie:
    name: SerieQueue
