server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: catalog-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

spring:
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false 

# Configuración para el listener de movie-service
spring:
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: false
    binding:
      listener:
        simple:
          queues:
            - name: ${queue.movie.name}
    queues:
      - name: ${queue.movie.name}
        durable: true

# Configuración para el listener de serie-service
spring:
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: false
    binding:
      listener:
        simple:
          queues:
            - name: ${queue.serie.name}
    queues:
      - name: ${queue.serie.name}
        durable: true
